import 'server-only';
import crypto from 'node:crypto';
import sanitizeHtml from 'sanitize-html';
import { db } from '@/lib/db';
import { audit } from '@/lib/audit';
import { newsSchema } from '@/schemas/news';

const clean = (html: string) => sanitizeHtml(html, { allowedTags: ['p', 'br', 'h2', 'h3', 'h4', 'strong', 'em', 'u', 's', 'ul', 'ol', 'li', 'blockquote', 'a', 'table', 'thead', 'tbody', 'tr', 'th', 'td'], allowedAttributes: { a: ['href', 'target', 'rel'], th: ['colspan', 'rowspan'], td: ['colspan', 'rowspan'] }, allowedSchemes: ['http', 'https', 'mailto'], transformTags: { a: (_tag, attrs) => ({ tagName: 'a', attribs: { ...attrs, rel: 'noopener noreferrer' } }) } });
const slugify = (title: string) => title.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 150);
const uniqueSlug = (title: string, id?: string) => { const base = slugify(title) || 'berita'; let slug = base, n = 2; while (db.prepare('SELECT 1 FROM news WHERE slug=? AND id<>?').get(slug, id ?? '')) slug = `${base}-${n++}`; return slug };
export function saveNews(actorId: string, id: string | undefined, input: unknown) { const data = newsSchema.parse(input); const content = clean(data.content); if (content.replace(/<[^>]*>/g, '').trim().length < 10) throw new Error('Isi berita terlalu pendek'); const time = new Date().toISOString(); if (id) { const old = db.prepare('SELECT * FROM news WHERE id=? AND deleted_at IS NULL').get(id) as Record<string, unknown> | undefined; if (!old) throw new Error('Berita tidak ditemukan'); const statusChanged = old.status !== data.status; db.prepare(`UPDATE news SET slug=?,title=?,excerpt=?,content_html=?,thumbnail_path=?,status=?,published_at=?,updated_at=? WHERE id=?`).run(uniqueSlug(data.title, id), data.title, data.excerpt, content, data.thumbnailPath || null, data.status, data.status === 'published' ? (old.published_at || time) : old.published_at, time, id); audit(statusChanged ? `news.${data.status === 'published' ? 'published' : 'unpublished'}` : 'news.updated', 'News', id, actorId, { title: old.title, status: old.status }, { title: data.title, status: data.status, thumbnailPath: data.thumbnailPath }); return id } const newId = crypto.randomUUID(); db.prepare(`INSERT INTO news (id,slug,title,excerpt,content_html,thumbnail_path,status,published_at,author_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).run(newId, uniqueSlug(data.title), data.title, data.excerpt, content, data.thumbnailPath || null, data.status, data.status === 'published' ? time : null, actorId, time, time); audit('news.created', 'News', newId, actorId, undefined, { title: data.title, status: data.status }); return newId }
export function deleteNews(actorId: string, id: string) { const old = db.prepare('SELECT id,title,status FROM news WHERE id=? AND deleted_at IS NULL').get(id); if (!old) throw new Error('Berita tidak ditemukan'); db.prepare('UPDATE news SET deleted_at=?,updated_at=? WHERE id=?').run(new Date().toISOString(), new Date().toISOString(), id); audit('news.deleted', 'News', id, actorId, old, undefined) }
