'use client';
import { useActionState, useState } from 'react';
import { Editor } from '@tinymce/tinymce-react';
import { Alert, Button, Form, Input, Select, Upload } from 'antd';
import type { UploadChangeParam } from 'antd/es/upload';
import { saveNewsAction, type NewsActionResult } from '@/app/actions/news';

type News={id?:string;title?:string;excerpt?:string;content_html?:string;thumbnail_path?:string|null;status?:string};
export function NewsEditorForm({news={}}:{news?:News}){const[content,setContent]=useState(news.content_html??'');const[thumbnail,setThumbnail]=useState(news.thumbnail_path??'');const[status,setStatus]=useState(news.status??'draft');const[state,action,pending]=useActionState(saveNewsAction,undefined);const upload=async(info:UploadChangeParam)=>{const file=info.file.originFileObj;if(!file)return;const data=new FormData();data.set('file',file);const response=await fetch('/api/admin/news/thumbnail',{method:'POST',body:data});const json=await response.json();if(!response.ok)throw new Error(json.error);setThumbnail(json.path)};return <form action={action}><Form component={false} layout='vertical'><input type='hidden' name='id' value={news.id??''}/><input type='hidden' name='content' value={content}/><input type='hidden' name='thumbnailPath' value={thumbnail}/><input type='hidden' name='status' value={status}/>{state&&<Alert className='mb-4' type={state.ok?'success':'error'} message={state.message}/>}<Form.Item label='Judul' required><Input name='title' required minLength={5} maxLength={180} defaultValue={news.title}/></Form.Item><Form.Item label='Ringkasan' required><Input.TextArea name='excerpt' required minLength={10} maxLength={400} rows={3} defaultValue={news.excerpt}/></Form.Item><Form.Item label='Thumbnail'><Upload accept='image/jpeg,image/png,image/webp' maxCount={1} customRequest={({onSuccess})=>onSuccess?.({})} onChange={upload}><Button>Pilih gambar</Button></Upload>{thumbnail&&<img src={thumbnail} alt='Pratinjau thumbnail' className='news-thumbnail-preview'/>}</Form.Item><Form.Item label='Isi berita' required><Editor tinymceScriptSrc='/tinymce/tinymce.min.js' licenseKey='gpl' value={content} onEditorChange={setContent} init={{height:480,menubar:false,plugins:'autolink lists link charmap preview anchor searchreplace visualblocks code fullscreen insertdatetime table help wordcount',toolbar:'undo redo | blocks | bold italic underline | bullist numlist | link blockquote table | removeformat | code fullscreen',base_url:'/tinymce',suffix:'.min'}}/></Form.Item><Form.Item label='Status'><Select value={status} onChange={setStatus} options={[{value:'draft',label:'Draft'},{value:'published',label:'Terbit'}]}/></Form.Item><Button type='primary' htmlType='submit' loading={pending}>Simpan berita</Button></Form></form>}
